from django.urls import path
from . import views
from .views.user_views import login_view, logout_view, whoami_view

urlpatterns = [
    path("users/", views.UserListCreate.as_view(), name="user-create-list"),
    path("users/<int:id_user>", views.UserRetrieveUpdateDestroy.as_view(), name="user-retrieve-update-destroy"),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/create', views.ProductCreateView.as_view(), name='product-create'),
    path("products/<str:id_product>", views.ProductRetrieveUpdateDestroy.as_view(), name="product-retrieve-update-destroy"),
    path('products/byCategory/<str:category>/', views.ProductByCategoryView.as_view()),
    path('products/bySubCategory/<str:subcategory>/', views.ProductBySubCategoryView.as_view()),
    path("subcategories/", views.SubCategoryListCreate.as_view(), name="subcategory-create-list"),
    path("subcategories/<int:id_subcategory>", views.SubCategoryRetrieveUpdateDestroy.as_view(), name="subcategory-retrieve-update-destroy"),
    path('subcategories/<int:id_subcategory>/products/', views.ProductsBySubCategory.as_view(), name='products-by-subcategory'),
    path("categories/", views.CategoryListCreate.as_view(), name="category-create-list"),
    path("categories/<int:id_category>", views.CategoryRetrieveUpdateDestroy.as_view(), name="category-retrieve-update-destroy"),
    path('categories/<int:id_category>/products/', views.ProductsByCategory.as_view(), name='products-by-category'),
    path("sales/", views.SaleListCreate.as_view(), name="sale-create-list"),
    path("sales/<int:id_sale>", views.SaleRetrieveUpdateDestroy.as_view(), name="sale-retrieve-update-destroy"),
    path("batches/", views.BatchListCreate.as_view(), name="batch-create-list"),
    path("batches/<int:id_batch>", views.BatchRetrieveUpdateDestroy.as_view(), name="batch-retrieve-update-destroy"),
    path('batches/expiring/', views.BatchExpiringSoonView.as_view()),
    path("sale_details/", views.SaleDetailListCreate.as_view(), name="sale_detail-create-list"),
    path("sale_details/sale/<int:sale_id>/product/<int:product_id>/", views.SaleDetailRetrieveUpdateDestroy.as_view(), name="sale_detail-retrieve-update-destroy"),
    path('sales/summary/MostSales/', views.Top10ProductsRevenue.as_view()),
    path('sales/summary/LeastSales/', views.Bottom10ProductsByRevenueView.as_view()),
    path('sales/summary/daily-report/', views.DailySalesReportView.as_view()),
    path('sales/report/product/', views.MonthlyRevenueVsCostByProductView.as_view(), name='monthly_report_by_product'),
    path('sales/report/category/', views.MonthlyRevenueVsCostByCategoryView.as_view(), name='monthly_report_by_category'),
    path('sales/report/gross-profit/', views.MonthlyGrossProfitView.as_view(), name='monthly_gross_profit'),
    path('sales/report/MostProfitable/', views.Top10MostProfitableProductsView.as_view(), name='monthly_most_profitable_products'),
    path('sales/report/ProductInventoryFlow/product/<int:product_id>', views.ProductInventoryFlowView.as_view(), name='monthly_product_inventory_flow'),
    path('sales/report/ProductSalesVariance/', views.ProductSalesVarianceView.as_view(), name='product_sales_variance'),
    path('sales/product/<int:id_product>/monthly/', views.MonthlyProductSalesView.as_view()),
    path("suppliers/", views.SupplierListCreate.as_view(), name="supplier-create-list"),
    path("suppliers/<str:rut>", views.SupplierRetrieveUpdateDestroy.as_view(), name="supplier-retrieve-update-destroy"),
    path("notifications/", views.NotificationListCreate.as_view(), name="notification-create-list"),
    path("notifications/<int:id_notification>", views.NotificationRetrieveUpdateDestroy.as_view(), name="notification-retrieve-update-destroy"),
    path('products-pdf/', views.ProductsPDFProcessingView.as_view(), name='products-pdf'),
    path('categories-pdf/', views.CategoriesPDFProcessingView.as_view(), name='categories-pdf'),
    path('suppliers-pdf/', views.SuppliersPDFProcessingView.as_view(), name='suppliers-pdf'),
    path('daily-stock-update/', views.DailyStockUpdate.as_view(), name='daily-stock-update'),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("whoami/", whoami_view, name="whoami"),
]