# Generated by Django 5.2 on 2025-05-15 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_stock_unit_product_entry_stock_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.DecimalField(decimal_places=0, max_digits=50, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
