# Generated by Django 5.2 on 2025-05-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_id_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='pending', max_length=50)),
                ('date_of_completion', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name_product', models.CharField(editable=False, max_length=150)),
                ('id_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.batch')),
            ],
        ),
    ]
