# Generated by Django 5.2 on 2025-06-05 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price_kilo',
            new_name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='composed_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='id_product must contain only digits.', regex='^\\d+$')]),
        ),
    ]
