# Generated by Django 5.2 on 2025-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_sale_price_kilo_product_sale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProcessedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
    ]
