# Generated by Django 5.2 on 2025-06-18 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lastprocessedreceipt_remove_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='starting_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='id_category',
            field=models.DecimalField(decimal_places=0, max_digits=50, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
