# Generated by Django 5.2 on 2025-06-19 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_batch_starting_quantity_alter_batch_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='starting_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
