# Generated by Django 5.2 on 2025-07-01 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_wrongsaledetail_remove_supplier_id_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrongsaledetail',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='lastprocessedreceipt',
            name='last_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='wrongsaledetail',
            name='barcode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
