# Generated by Django 5.2 on 2025-07-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_wrongsaledetail_receipt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='checked',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
